### ISSUE TITLE
500 error on wheelmap.org/api/categories/1/node_types

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#148]
- I call http://wheelmap.org/api/categories/1/node_types?api_key=MYAPIKEY&per_page=6 in my browser where MYAPIKEY ist the key I got from my profile page
- I expect to see a result set.
- Instead, I get a 500 error. Other API request with my API key seem to work, for example http://wheelmap.org/api/nodes/3325161208?api_key=MYAPIKEY

**Comment by schultyy** [comment]
I had a look into the errors reported by Airbrake and this one seems to be the related error:
Message: `NoMethodError: undefined method `find' for Api::Category:Module`

Backtrace:
```
/gems/inherited_resources-1.6.0/lib/inherited_resources/belongs_to_helpers.rb:90 in evaluate_parent
/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb:144 in block in association_chain
/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb:143 in each
/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb:143 in inject
/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb:143 in association_chain
/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb:182 in end_of_association_chain
app/controllers/api/node_types_controller.rb:25 in collection
/gems/inherited_resources-1.6.0/lib/inherited_resources/actions.rb:7 in index
app/controllers/api/node_types_controller.rb:9 in index
/gems/actionpack-3.2.22.1/lib/action_controller/metal/implicit_render.rb:4 in send_action
/gems/actionpack-3.2.22.1/lib/abstract_controller/base.rb:167 in process_action
/gems/actionpack-3.2.22.1/lib/action_controller/metal/rendering.rb:10 in process_action
/gems/actionpack-3.2.22.1/lib/abstract_controller/callbacks.rb:18 in block in process_action
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:536 in block in _run__2411499972943141399__process_action__2813212777823120052__callbacks
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:215 in block in _conditional_callback_around_740
/gems/cacheable_flash-0.3.4/lib/cacheable_flash.rb:31 in write_flash_to_cookie
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:214 in _conditional_callback_around_740
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:425 in _run__2411499972943141399__process_action__2813212777823120052__callbacks
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:405 in __run_callback
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:385 in _run_process_action_callbacks
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/actionpack-3.2.22.1/lib/abstract_controller/callbacks.rb:17 in process_action
/gems/actionpack-3.2.22.1/lib/action_controller/metal/rescue.rb:29 in process_action
/gems/actionpack-3.2.22.1/lib/action_controller/metal/instrumentation.rb:30 in block in process_action
/gems/activesupport-3.2.22.1/lib/active_support/notifications.rb:123 in block in instrument
/gems/activesupport-3.2.22.1/lib/active_support/notifications/instrumenter.rb:20 in instrument
/gems/activesupport-3.2.22.1/lib/active_support/notifications.rb:123 in instrument
/gems/actionpack-3.2.22.1/lib/action_controller/metal/instrumentation.rb:29 in process_action
/gems/actionpack-3.2.22.1/lib/action_controller/metal/params_wrapper.rb:207 in process_action
/gems/activerecord-3.2.22.1/lib/active_record/railties/controller_runtime.rb:18 in process_action
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30 in block in process_action
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362 in perform_action_with_newrelic_trace
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25 in process_action
/gems/actionpack-3.2.22.1/lib/abstract_controller/base.rb:121 in process
/gems/actionpack-3.2.22.1/lib/abstract_controller/rendering.rb:45 in process
/gems/actionpack-3.2.22.1/lib/action_controller/metal.rb:203 in dispatch
/gems/actionpack-3.2.22.1/lib/action_controller/metal/rack_delegation.rb:14 in dispatch
/gems/actionpack-3.2.22.1/lib/action_controller/metal.rb:246 in block in action
/gems/actionpack-3.2.22.1/lib/action_dispatch/routing/route_set.rb:73 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/routing/route_set.rb:73 in dispatch
/gems/actionpack-3.2.22.1/lib/action_dispatch/routing/route_set.rb:36 in call
/gems/journey-1.0.4/lib/journey/router.rb:68 in block in call
/gems/journey-1.0.4/lib/journey/router.rb:56 in each
/gems/journey-1.0.4/lib/journey/router.rb:56 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/routing/route_set.rb:608 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/apipie-rails-0.3.5/lib/apipie/static_dispatcher.rb:65 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186 in call!
/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/apipie-rails-0.3.5/lib/apipie/extractor/recorder.rb:132 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/rack/agent_hooks.rb:30 in traced_call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/rack/browser_monitoring.rb:32 in traced_call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
lib/rack_i18n_locale_switcher.rb:32 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/warden-1.2.6/lib/warden/manager.rb:35 in block in call
/gems/warden-1.2.6/lib/warden/manager.rb:34 in catch
/gems/warden-1.2.6/lib/warden/manager.rb:34 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/best_standards_support.rb:17 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/etag.rb:23 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/conditionalget.rb:25 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/head.rb:14 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/params_parser.rb:21 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/flash.rb:242 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210 in context
/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/flash_cookie_session-1.1.6/lib/flash_cookie_session/middleware.rb:30 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/cookies.rb:341 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/activerecord-3.2.22.1/lib/active_record/query_cache.rb:64 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/activerecord-3.2.22.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:479 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/callbacks.rb:28 in block in call
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:405 in _run__2908315273751808178__call__2989315654728332339__callbacks
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:405 in __run_callback
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:385 in _run_call_callbacks
/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/callbacks.rb:27 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/sendfile.rb:102 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/remote_ip.rb:31 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/debug_exceptions.rb:16 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/show_exceptions.rb:56 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/railties-3.2.22.1/lib/rails/rack/logger.rb:32 in call_app
/gems/railties-3.2.22.1/lib/rails/rack/logger.rb:16 in block in call
/gems/activesupport-3.2.22.1/lib/active_support/tagged_logging.rb:22 in tagged
/gems/railties-3.2.22.1/lib/rails/rack/logger.rb:16 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/request_id.rb:22 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/methodoverride.rb:21 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/runtime.rb:17 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/activesupport-3.2.22.1/lib/active_support/cache/strategy/local_cache.rb:72 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-1.4.7/lib/rack/lock.rb:15 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140 in forward
/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249 in fetch
/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189 in lookup
/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66 in call!
/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/librato-rack-0.6.0/lib/librato/rack.rb:94 in process_request
/gems/librato-rack-0.6.0/lib/librato/rack.rb:64 in call
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/railties-3.2.22.1/lib/rails/engine.rb:484 in call
/gems/railties-3.2.22.1/lib/rails/application.rb:231 in call
/gems/railties-3.2.22.1/lib/rails/railtie/configurable.rb:30 in method_missing
/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96 in call
/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562 in process_client
/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658 in worker_loop
/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508 in spawn_missing_workers
/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132 in start
/gems/unicorn-5.0.1/bin/unicorn:126 in <top (required)>
[GEM_ROOT]/bin/unicorn:23 in load
[GEM_ROOT]/bin/unicorn:23 in <main>
```

Params: 

```
{
  "action": "index",
  "api_key": "[FILTERED]",
  "category_id": "1",
  "controller": "api/node_types",
  "format": "json",
  "page": "1",
  "per_page": "6"
}
```

**Comment by lennerd** [comment]
Via `git bisect` I found out, that the error was introduced by 8cd67942b7c1188284c16ab97b1275b8a66b0c8c.

If you want to test this yourself, don't forget to restart the server between every iteration.

**Comment by lennerd** [comment]
@holgerd Does this fix the issue for you on staging? If yes, I would like to deploy this in production.

**Comment by lennerd** [comment]
@holgerd ping

**Comment by holgerd** [comment]
yes now it works on staging!

**Comment by lennerd** [comment]
Fix is deployed on production.

**Comment by holgerd** [comment]
On August 28, 2016 I got the exact same bug report again (via Jonas) so I reopen this issue:

>  there is a server error coming up whenever I try and get the nodes for a category...
> 
> http://wheelmap.org/api/categories/9/nodes?api_key=[APIKEY]&locale=en&bbox=8.6592776,49.4077793,8.679277599999999,49.4277793
> 
> if I do it without the category filter it works ok
> 
> http://wheelmap.org/api/nodes?api_key=[APIKEY]&locale=en&bbox=8.6592776,49.4077793,8.679277599999999,49.4277793
> 
> I can't remember who it was I got in touch with last time there was an issue, so I thought you would be the best person to start with :p

**Comment by holgerd** [comment]
From Adam:

______

just doing last minute checks of the apps before the review, and I notice that the wheelmap API doesn't work when getting nodes for a particular category...

https://wheelmap.org/api/categories/1/nodes?api_key=APIKEY&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes


it works when just getting all nodes though:

https://wheelmap.org/api/nodes?api_key=APIKEY&bbox=13.341,52.505,13.434,52.523&per_page=10&wheelchair=yes

**Comment by 1000miles** [comment]
@holgerd 

Following are the infos we can provide after our short research today:

**Browser Err output**

`{"status":"500","error":"Internal Server Error"}`

**Server Err Log:**
```
I, [2017-01-10T14:47:58.537223 #32303]  INFO -- : Started GET "/api/categories/1/node_types?api_key=[FILTERED]" for xx.xx.xx.xx at 2017-01-10 14:47:58 +0100 I, [2017-01-10T14:47:58.544725 #32303]  INFO -- : Processing by Api::NodeTypesController#index as HTML I, [2017-01-10T14:47:58.544814 #32303]  INFO -- :   Parameters: {"api_key"=>"[FILTERED]", "category_id"=>"1"} I, [2017-01-10T14:47:58.549525 #32303]  INFO -- : Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.6ms) F, [2017-01-10T14:47:58.561910 #32303] FATAL -- : NoMethodError (undefined method `find' for Api::Category:Module):  app/controllers/api/node_types_controller.rb:25:in `collection'  app/controllers/api/node_types_controller.rb:9:in `index'  lib/rack_i18n_locale_switcher.rb:32:in `call'  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

**Assumption:**
- a) error is not user-related (tested with 2 different api keys)
- b) error is not data-related (tested with different and no params)
- c) error occurs permanently 
      - `/api/categories/1/node_types?api_key=APIKEY`
      - `/api/categories/2/node_types?api_key=APIJEY2`
      - `/api/categories/999/node_types?api_key=APIJEY3`


**Estimation to fix this:**
- ca. 1/2 project day
