### ISSUE TITLE
ActiveAdmin: RuntimeError in Regions#Index

### ISSUE THREAD

**Issue by schultyy** [sozialhelden/wheelmap#243]
RuntimeError in Admin/regions#index

Showing /home/vagrant/wheelmap/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre2/app/views/active_admin/resource/index.html.arb where line #2 raised:

`default_actions` is no longer provided in ActiveAdmin 1.x. Use `actions` instead.

Extracted source (around line #2):

1: insert_tag renderer_for(:index)

Rails.root: /home/vagrant/wheelmap
Application Trace | Framework Trace | Full Trace

app/admin/region.rb:21:in `block (2 levels) in <top (required)>'
lib/rack_i18n_locale_switcher.rb:32:in `call'

Request

Parameters:

None

**Comment by schultyy** [comment]
Related to #244

**Comment by schultyy** [comment]
Fixed in 6ff198050058d8ef31433ee0cb7ed7458f234b39
