### ISSUE TITLE
[active_admin]: ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=boeblingen)

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#454]
Yay, we found another bug. :) 

- I am logged in in active admin dashboard on  `production` & `staging`
- I go to the page region and select `Boeblingen` out of the list
- I click on the `Boeblingen` detail page (https://wheelmap.org/admin/regions/boeblingen/)
- I click on the `photos` link
- I get the "famous" error page `The page you were looking for doesn't exist.`

**Error log output on the server:**
```
I, [2016-10-21T13:53 #29543]  INFO -- : Started GET "/admin/regions/kreis-boeblingen/photos" for xxxx at 2016-10-21 13:53:14 +0200
I, [2016-10-21T13:53 #29543]  INFO -- : Processing by Admin::PhotosController#index as HTML
I, [2016-10-21T13:53 #29543]  INFO -- :   Parameters: {"region_id"=>"kreis-boeblingen"}
I, [2016-10-21T13:53 #29543]  INFO -- : Completed 404 Not Found in 4ms (ActiveRecord: 0.4ms)
F, [2016-10-21T13:53:14.699924 #29543] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=kreis-boeblingen):
  app/admin/photos.rb:13:in `collection'
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

P.S. Boeblingen is just an example. The same error applies to following cities we tested as well:
- hamburg (not touched during our wkt-renaming process)
```
F, [2016-10-21T13:53:47.978222 #30537] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=hamburg):
  app/admin/photos.rb:13:in `collection'
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```
- bremen

```
F, [2016-10-21T13:54:00.895130 #29560] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=bremen):
  app/admin/photos.rb:13:in `collection'
  lib/rack_i18n_locale_switcher.rb:32:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

**Comment by 1000miles** [comment]
More examples where the photos controller in admin dashboard is affected.

- Zuerich
- Osnabrueck
- Moskau
- Dublin

```shell
F, [2017-05-18T16:58:56.282751 #5864] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Region with 'id'=dublin):
  app/admin/photos.rb:13:in `collection'
  lib/rack_i18n_locale_switcher.rb:29:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'

```

<img width="1267" alt="screen shot 2017-05-18 at 16 57 44" src="https://cloud.githubusercontent.com/assets/4077916/26208876/8073937c-3beb-11e7-9aaa-471c158ea04f.png">
<img width="1270" alt="screen shot 2017-05-18 at 16 58 25" src="https://cloud.githubusercontent.com/assets/4077916/26208877/807bb1ce-3beb-11e7-989e-17bda24ebb61.png">
<img width="1267" alt="screen shot 2017-05-18 at 16 58 59" src="https://cloud.githubusercontent.com/assets/4077916/26208878/80a9f4bc-3beb-11e7-8cb6-cd6f4e820f88.png">
