### ISSUE TITLE
Staging deployment fails due to 'Gemfile not found (Bundler::GemfileNotFound)' 

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#627]
Since friday, 2017-06-09, we can not deploy to staging. According to this line it tries to fetch the Gemfile from an older release multiple times:

```bash
opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /[obfuscated]/staging/releases/20170504104709/Gemfile not found (Bundler::GemfileNotFound)
```

One of the suggested solutions could be to set a before_exec hook for the `Gemfile` as mentioned here:
- https://github.com/tablexi/capistrano3-unicorn/issues/30
- https://stackoverflow.com/questions/30002151/gemfile-not-found-when-running-cron-job-with-capistrano-3-and-whenever-gem

----

### Full error output:

```bash
I, [2017-06-08T08:14:07.159189 #20868]  INFO -- : reaped #<Process::Status: pid 20899 exit 0> worker=0
I, [2017-06-08T08:14:07.159319 #20868]  INFO -- : master complete
I, [2017-06-09T15:18:24.670390 #25513]  INFO -- : executing ["/[obfuscated]/staging/shared/bundle/ruby/2.2.0/bin/unicorn", "-c", "/[obfuscated]/staging/current/config/unicorn.rb", "-E", "staging", "-D", {16=>#<Kgio::UNIXServer:fd 16>}] (in /[obfuscated]/staging/releases/20170609131351)
I, [2017-06-09T15:18:24.706977 #25513]  INFO -- : forked child re-executing...
/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /[obfuscated]/staging/releases/20170504104709/Gemfile not found (Bundler::GemfileNotFound)
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
E, [2017-06-09T15:18:25.032912 #28155] ERROR -- : reaped #<Process::Status: pid 25513 exit 1> exec()-ed
I, [2017-06-09T15:52:55.510489 #10573]  INFO -- : executing ["/[obfuscated]/staging/shared/bundle/ruby/2.2.0/bin/unicorn", "-c", "/[obfuscated]/staging/current/config/unicorn.rb", "-E", "staging", "-D", {16=>#<Kgio::UNIXServer:fd 16>}] (in /[obfuscated]/staging/releases/20170609135100)
I, [2017-06-09T15:52:55.510613 #10573]  INFO -- : forked child re-executing...
/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /[obfuscated]/staging/releases/20170504104709/Gemfile not found (Bundler::GemfileNotFound)
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
E, [2017-06-09T15:52:55.687890 #28155] ERROR -- : reaped #<Process::Status: pid 10573 exit 1> exec()-ed
I, [2017-06-12T10:37:51.476344 #7105]  INFO -- : executing ["/[obfuscated]/staging/shared/bundle/ruby/2.2.0/bin/unicorn", "-c", "/[obfuscated]/staging/current/config/unicorn.rb", "-E", "staging", "-D", {16=>#<Kgio::UNIXServer:fd 16>}] (in /[obfuscated]/staging/releases/20170612083357)
I, [2017-06-12T10:37:51.496346 #7105]  INFO -- : forked child re-executing...
/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /[obfuscated]/staging/releases/20170504104709/Gemfile not found (Bundler::GemfileNotFound)
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
	from /opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
E, [2017-06-12T10:37:51.696135 #28155] ERROR -- : reaped #<Process::Status: pid 7105 exit 1> exec()-ed
```

**Comment by 1000miles** [comment]
@opyh :)

Deployed to staging with release [20170612134158](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170612134158) today.

According to the current logs the PR #628 fixed this.

```bash
I, [2017-06-12T15:41:21.704078 #28985]  INFO -- : executing ["/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/bin/unicorn", "-c", "/var/apps/wheelmap/staging/current/config/unicorn.rb", "-E", "staging", "-D", {16=>#<Kgio::UNIXServer:/var/apps/wheelmap/staging/shared/unicorn.sock>}] (in /var/apps/wheelmap/staging/releases/20170612133849)
I, [2017-06-12T15:41:22.072433 #28985]  INFO -- : inherited addr=/var/apps/wheelmap/staging/shared/unicorn.sock fd=16
I, [2017-06-12T15:41:22.072599 #28985]  INFO -- : Refreshing Gem list
I, [2017-06-12T15:41:26.278460 #28985]  INFO -- : master process ready
I, [2017-06-12T15:41:26.302392 #29010]  INFO -- : worker=0 ready
I, [2017-06-12T15:41:26.676160 #32079]  INFO -- : reaped #<Process::Status: pid 32084 exit 0> worker=0
I, [2017-06-12T15:41:26.676282 #32079]  INFO -- : master complete
```
